default: true

# Line length
MD013: false

# Inline HTML
MD033: false

# First line in file should be a top level heading
MD041: false

# Multiple headings with the same content
MD024: false

# Multiple top-level headings in the same document
MD025: false

# Code block style
MD046: false

# Images should have alternate text (alt text)
MD045: false

# Emphasis used instead of a heading
MD036: false
